
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 15 20:43:16 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESSTHEN = 40;
  public static final int LBRACKET = 31;
  public static final int INCREMENT = 44;
  public static final int CONST = 48;
  public static final int ASTERISK = 33;
  public static final int SLASH = 34;
  public static final int NOTEQUAL = 37;
  public static final int LPAREN = 27;
  public static final int SEMI = 26;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 14;
  public static final int DECREMENT = 45;
  public static final int FOR = 16;
  public static final int MINUS = 32;
  public static final int CHARACTER = 47;
  public static final int RPAREN = 25;
  public static final int AND = 42;
  public static final int GRTTHEN = 38;
  public static final int OR = 43;
  public static final int COMMA = 29;
  public static final int CLASS = 6;
  public static final int LESSEQUALTHEN = 41;
  public static final int PLUS = 23;
  public static final int ASSIGN = 22;
  public static final int IF = 8;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 36;
  public static final int RBRACKET = 30;
  public static final int TRUE = 20;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PERCENT = 35;
  public static final int NUMBER = 2;
  public static final int BREAK = 5;
  public static final int IDENT = 3;
  public static final int VOID = 12;
  public static final int LBRACE = 28;
  public static final int ELSE = 7;
  public static final int ENUM = 15;
  public static final int READ = 11;
  public static final int RBRACE = 24;
  public static final int EXTENDS = 17;
  public static final int PROG = 4;
  public static final int FALSE = 21;
  public static final int IMPLEMENTS = 13;
  public static final int PRINT = 10;
  public static final int GRTEQUALTHEN = 39;
}

